services:
  hercules_server:
    build: .
    image: hercules:v01
    container_name: hercules_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports:
      - 5000:5000
    networks: 
      - hercules_net
    restart: unless-stopped
    depends_on: 
      - hercules_psql
      - hercules_redis
  
  hercules_psql:
    image: postgres
    container_name: hercules_psql
    volumes: 
      - hercules_psql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=creepak
      - POSTGRES_DB=hercules
      - POSTGRES_PASSWORD=7856pass7856
    networks: 
      - hercules_net
    restart: unless-stopped

  hercules_redis:
    image: redis
    container_name: hercules_redis
    networks:
      - hercules_net
    restart: unless-stopped

volumes:
  hercules_psql:
    name: hercules_psql

networks:
  hercules_net:
    name: hercules_net
    driver: bridge
